# Generated by Django 4.2 on 2023-04-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='lm_authors',
        ),
    ]
