# Generated by Django 4.2 on 2023-04-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_language'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='bookinstance',
            table='book_instances',
        ),
    ]
