# Generated by Django 4.2 on 2023-04-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_table_alter_bookinstance_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='lm_books',
        ),
        migrations.AlterModelTable(
            name='bookinstance',
            table='lm_book_instances',
        ),
    ]
